version: '3.7'

services:
  web:
    build:
      context: .
    ports:
      - "4200:4200"
    working_dir: /root/app
    environment:
      HOST: localhost
      PORT: 4200
      GOOGLE_CREDIENTIAL_JSON_BASE64: ""
      GOOGLE_ANALYTICS_VIEW_ID: ""
    volumes:
      - ./app:/root/app
      - ./scripts:/root/app/scripts
      - node_modules:/root/app/node_modules
    command: develop

volumes:
  node_modules:
    driver: local
  resumes:
    driver: local
